"""
Endpoint tests for the web UI (server.py).

The fixture builds a tiny real library in a tmp dir: a 1-second silent MP3
generated by ffmpeg and tagged with mutagen. A real MP3 matters — a fake-header
or zero-byte file makes browse._read_tags hit its except path and return {},
which would silently pass a broken read.
"""
import shutil
import subprocess
import time
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

import server
from mutagen.id3 import ID3, TIT2, TPE1, TPE2, TALB, TYER, TRCK

_FRAMES = {"TIT2": TIT2, "TPE1": TPE1, "TPE2": TPE2,
           "TALB": TALB, "TYER": TYER, "TRCK": TRCK}


def _make_mp3(path, **frames):
    """Create a real (ffmpeg) MP3 at *path* tagged with *frames* (defaults given)."""
    if not frames:
        frames = {"TIT2": "Silent Night", "TPE1": "Test Artist", "TPE2": "Test Artist",
                  "TALB": "Test Album", "TYER": "2024", "TRCK": "01/1"}
    path.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
         "-f", "lavfi", "-i", "anullsrc=r=44100:cl=stereo",
         "-t", "1", "-q:a", "9", str(path)],
        check=True,
    )
    tags = ID3()
    for fid, val in frames.items():
        tags.add(_FRAMES[fid](encoding=3, text=val))
    tags.save(path, v2_version=3, v1=0)


def _poll(client, jid, answer=None, max_iter=400):
    """Drive a job to a terminal state, answering prompts via answer(prompt)->value."""
    for _ in range(max_iter):
        j = client.get(f"/api/jobs/{jid}").json()
        if j["state"] == "waiting":
            val = answer(j["prompt"]) if answer else ""
            client.post(f"/api/jobs/{jid}/respond", json={"value": val})
        elif j["state"] in ("done", "error"):
            return j
        time.sleep(0.03)
    return client.get(f"/api/jobs/{jid}").json()


@pytest.fixture()
def client(tmp_path):
    if shutil.which("ffmpeg") is None:
        pytest.skip("ffmpeg not available")
    album = tmp_path / "Test Artist" / "2024 - Test Album"
    album.mkdir(parents=True)
    _make_mp3(album / "01. Test Artist - Silent Night.mp3")
    server.set_root(tmp_path)
    return TestClient(server.app)


def test_tree_shape(client):
    data = client.get("/api/tree").json()
    assert data["artists"], "expected at least one artist"
    artist = data["artists"][0]
    assert artist["kind"] == "artist"
    assert artist["label"] == "Test Artist"
    album = artist["children"][0]
    assert album["kind"] == "album"
    track = album["children"][0]
    assert track["kind"] == "track"
    assert track["path"].endswith(".mp3")


def test_album_reads_real_tags(client):
    tree = client.get("/api/tree").json()
    album_path = tree["artists"][0]["children"][0]["path"]
    data = client.get("/api/album", params={"path": album_path}).json()
    assert len(data["tracks"]) == 1
    t = data["tracks"][0]
    # A real MP3 must yield populated tags, not the {} except-path.
    assert t["title"] == "Silent Night"
    assert t["artist"] == "Test Artist"
    assert t["album"] == "Test Album"
    assert t["year"] == "2024"


def test_tag_write_read_roundtrip(client):
    tree = client.get("/api/tree").json()
    album_path = tree["artists"][0]["children"][0]["path"]
    track_path = client.get("/api/album", params={"path": album_path}).json()["tracks"][0]["path"]

    resp = client.post("/api/tags", json={
        "path": track_path,
        "updates": {"TIT2": "Renamed Title", "TPE1": "Renamed Artist"},
    })
    assert resp.status_code == 200
    assert resp.json()["title"] == "Renamed Title"

    # Re-read independently to prove it persisted to disk.
    again = client.get("/api/album", params={"path": album_path}).json()["tracks"][0]
    assert again["title"] == "Renamed Title"
    assert again["artist"] == "Renamed Artist"


def test_safe_rejects_outside_root(client):
    resp = client.get("/api/album", params={"path": "/etc"})
    assert resp.status_code == 403


def test_track_streams_audio(client):
    tree = client.get("/api/tree").json()
    album = tree["artists"][0]["children"][0]["path"]
    track = client.get("/api/album", params={"path": album}).json()["tracks"][0]["path"]

    full = client.get("/api/track", params={"path": track})
    assert full.status_code == 200
    assert full.headers["content-type"] == "audio/mpeg"
    assert full.headers.get("accept-ranges") == "bytes"

    # Range request → 206 partial content (enables seeking).
    part = client.get("/api/track", params={"path": track}, headers={"Range": "bytes=0-99"})
    assert part.status_code == 206
    assert "content-range" in part.headers
    assert len(part.content) == 100


def test_track_rejects_outside_root(client):
    assert client.get("/api/track", params={"path": "/etc/passwd"}).status_code == 403


def test_settings_roundtrip(client):
    client.post("/api/settings", json={"cover_art": "both"})
    assert client.get("/api/settings").json()["cover_art"] == "both"


# ── Structural edits ──────────────────────────────────────────────────────────

def test_edit_track_title_renames_file(client):
    tree = client.get("/api/tree").json()
    album_path = tree["artists"][0]["children"][0]["path"]
    track_path = client.get("/api/album", params={"path": album_path}).json()["tracks"][0]["path"]

    resp = client.post("/api/edit/apply",
                       json={"path": track_path, "op": "track_title", "value": "Brand New"})
    assert resp.status_code == 200 and resp.json()["ok"]

    again = client.get("/api/album", params={"path": album_path}).json()["tracks"][0]
    assert again["title"] == "Brand New"
    assert again["path"].endswith("Brand New.mp3")  # file was renamed


def test_edit_album_year_moves_folder(client, tmp_path):
    tree = client.get("/api/tree").json()
    album_path = tree["artists"][0]["children"][0]["path"]
    resp = client.post("/api/edit/apply",
                       json={"path": album_path, "op": "album_year", "value": "1999"})
    body = resp.json()
    assert body["ok"]
    # new_path reports the moved folder and it exists on disk.
    assert body["new_path"] != album_path
    assert body["new_path"].endswith("1999 - Test Album")
    from pathlib import Path
    assert Path(body["new_path"]).is_dir()
    artist_dir = tmp_path / "Test Artist"
    names = sorted(p.name for p in artist_dir.iterdir())
    assert any(n.startswith("1999 - ") for n in names)


def test_edit_album_genre_keeps_path(client):
    tree = client.get("/api/tree").json()
    album_path = tree["artists"][0]["children"][0]["path"]
    resp = client.post("/api/edit/apply",
                       json={"path": album_path, "op": "album_genre", "value": "Jazz"})
    body = resp.json()
    assert body["ok"]
    # genre is a tag-only edit — folder does not move.
    assert body["new_path"] == album_path


def test_edit_unknown_op_400(client):
    tree = client.get("/api/tree").json()
    album_path = tree["artists"][0]["children"][0]["path"]
    resp = client.post("/api/edit/apply",
                       json={"path": album_path, "op": "bogus", "value": "x"})
    assert resp.status_code == 400


# ── Audit ─────────────────────────────────────────────────────────────────────

def test_audit_returns_categories(client):
    data = client.get("/api/audit").json()
    assert "category_labels" in data and data["category_labels"]
    assert set(data["totals"]) == {"albums", "albums_with_issues", "files", "files_with_issues"}


# ── Jobs ──────────────────────────────────────────────────────────────────────

def test_standardize_dry_run_job(client):
    jid = client.post("/api/jobs", json={"kind": "standardize", "dry_run": True}).json()["job_id"]
    j = _poll(client, jid)
    assert j["state"] == "done", j.get("error")
    assert j["log"], "expected captured log output"


def test_standardize_prompt_roundtrip(tmp_path):
    if shutil.which("ffmpeg") is None:
        pytest.skip("ffmpeg not available")
    # A file missing TIT2 forces step 2 (fix missing tags) to prompt.
    album = tmp_path / "Artist" / "2024 - Album"
    _make_mp3(album / "01. Artist - Track.mp3",
              TPE1="Artist", TPE2="Artist", TALB="Album", TYER="2024", TRCK="01/1")
    server.set_root(tmp_path)
    c = TestClient(server.app)

    asked = []

    def answer(prompt):
        asked.append(prompt["kind"])
        if prompt["kind"] == "text" and "Title" in prompt["prompt"]:
            return "Filled In"
        if prompt["kind"] == "choice" and prompt["options"]:
            return prompt["options"][0]["key"]
        return ""

    jid = c.post("/api/jobs", json={"kind": "standardize", "dry_run": False}).json()["job_id"]
    j = _poll(c, jid, answer)
    assert j["state"] == "done", j.get("error")
    assert "text" in asked, "expected at least one text prompt"
    # The title we supplied should now be on disk (file likely renamed to match).
    written = list((tmp_path / "Artist").rglob("*.mp3"))
    assert written
    tags = ID3(written[0], translate=False)
    assert str(tags.get("TIT2")) == "Filled In"


def test_import_job_copies_file(tmp_path, tmp_path_factory):
    if shutil.which("ffmpeg") is None:
        pytest.skip("ffmpeg not available")
    src = tmp_path_factory.mktemp("source")
    _make_mp3(src / "song.mp3", TIT2="Imported", TPE1="Imp", TPE2="Imp",
              TALB="ImpAlbum", TYER="2020", TRCK="1")
    server.set_root(tmp_path)
    c = TestClient(server.app)

    def answer(prompt):
        if prompt["kind"] == "preview":
            return {"proceed": True, "entries": prompt["entries"]}
        if prompt["kind"] == "choice" and prompt["options"]:
            return prompt["options"][0]["key"]
        return ""

    jid = c.post("/api/jobs",
                 json={"kind": "import", "source": str(src), "dry_run": False}).json()["job_id"]
    j = _poll(c, jid, answer)
    assert j["state"] == "done", j.get("error")
    imported = list(tmp_path.rglob("*.mp3"))
    assert imported, "expected an imported file in the library"


def test_second_job_conflict(client):
    # Start an import that will block on the preview prompt, then a second start -> 409.
    # Use a source with one file so it reaches the preview and waits.
    import tempfile
    src = tempfile.mkdtemp()
    _make_mp3(__import__("pathlib").Path(src) / "s.mp3",
              TIT2="A", TPE1="B", TPE2="B", TALB="C", TYER="2020", TRCK="1")
    first = client.post("/api/jobs", json={"kind": "import", "source": src}).json()["job_id"]
    # wait until it is waiting on preview
    for _ in range(200):
        if client.get(f"/api/jobs/{first}").json()["state"] == "waiting":
            break
        time.sleep(0.02)
    resp = client.post("/api/jobs", json={"kind": "standardize", "dry_run": True})
    assert resp.status_code == 409
    client.post(f"/api/jobs/{first}/cancel")  # release
    shutil.rmtree(src, ignore_errors=True)


# ── Sync ──────────────────────────────────────────────────────────────────────

def _sync_client(tmp_path):
    if shutil.which("ffmpeg") is None:
        pytest.skip("ffmpeg not available")
    _make_mp3(tmp_path / "Artist One" / "2019 - First" / "01. A - S.mp3")
    _make_mp3(tmp_path / "Artist One" / "2021 - Second" / "01. A - S.mp3")
    _make_mp3(tmp_path / "Artist Two" / "2020 - Solo" / "01. A - S.mp3")
    server.set_root(tmp_path)
    return TestClient(server.app)


def test_sync_artists_and_albums(tmp_path, tmp_path_factory):
    c = _sync_client(tmp_path)
    dev = tmp_path_factory.mktemp("device")
    data = c.get("/api/sync/artists", params={"device": str(dev)}).json()
    names = sorted(a["name"] for a in data["artists"])
    assert names == ["Artist One", "Artist Two"]
    assert all(a["status"] == "not on device" for a in data["artists"])

    albums = c.get("/api/sync/albums",
                   params={"artist": str(tmp_path / "Artist One"), "device": str(dev)}).json()
    assert albums["has_albums"]
    assert sorted(x["name"] for x in albums["albums"]) == ["2019 - First", "2021 - Second"]


def test_sync_plan_and_job_copies(tmp_path, tmp_path_factory):
    c = _sync_client(tmp_path)
    dev = tmp_path_factory.mktemp("device")
    selection = {
        str(tmp_path / "Artist One"): "all",
        str(tmp_path / "Artist Two"): [str(tmp_path / "Artist Two" / "2020 - Solo")],
    }
    plan = c.post("/api/sync/plan", json={"device": str(dev), "selection": selection}).json()
    assert plan["copy_files"] == 3 and plan["enough_space"]

    jid = c.post("/api/jobs",
                 json={"kind": "sync", "device": str(dev), "selection": selection}).json()["job_id"]
    j = _poll(c, jid)
    assert j["state"] == "done", j.get("error")
    copied = sorted(str(p.relative_to(dev)) for p in dev.rglob("*.mp3"))
    assert copied == [
        "Artist One/2019 - First/01. A - S.mp3",
        "Artist One/2021 - Second/01. A - S.mp3",
        "Artist Two/2020 - Solo/01. A - S.mp3",
    ]


def test_sync_device_inside_library_rejected(tmp_path):
    c = _sync_client(tmp_path)
    resp = c.get("/api/sync/artists", params={"device": str(tmp_path / "Artist One")})
    assert resp.status_code == 400


def test_sync_eta_helper():
    from webjobs import _eta, _fmt_duration
    assert _fmt_duration(95) == "1:35"
    assert _fmt_duration(3725) == "1:02:05"
    assert _eta(0, 100, 10) == ""          # nothing copied yet
    assert _eta(100, 100, 10) == ""        # finished
    assert _eta(50, 100, 0.2) == ""        # too early to estimate
    assert _eta(50, 100, 1.0) == " · ETA 0:01"   # half done in 1s → ~1s left


def test_sync_devices_endpoint(client):
    data = client.get("/api/sync/devices").json()
    assert "devices" in data and isinstance(data["devices"], list)


def test_device_rows_excludes_library(tmp_path, monkeypatch):
    import sync_library
    inside = tmp_path / "Artist"
    inside.mkdir()
    fake = [
        {"path": tmp_path, "free": 1, "total": 2},                 # the library itself
        {"path": inside, "free": 1, "total": 2},                   # inside the library
        {"path": Path("/run/media/x/USB"), "free": 100, "total": 200},
    ]
    monkeypatch.setattr(sync_library, "detect_devices", lambda: fake)
    rows = sync_library.device_rows(exclude=tmp_path)
    paths = [r["path"] for r in rows]
    assert str(tmp_path) not in paths
    assert str(inside) not in paths
    assert "/run/media/x/USB" in paths
    assert rows[0]["name"] == "USB" and rows[0]["free_h"]


def test_edits_blocked_while_job_active(client, tmp_path):
    # Start an import that parks on the preview prompt, so a job is "active".
    import tempfile
    src = tempfile.mkdtemp()
    _make_mp3(Path(src) / "s.mp3", TIT2="A", TPE1="B", TPE2="B",
              TALB="C", TYER="2020", TRCK="1")
    jid = client.post("/api/jobs", json={"kind": "import", "source": src}).json()["job_id"]
    for _ in range(200):
        if client.get(f"/api/jobs/{jid}").json()["state"] == "waiting":
            break
        time.sleep(0.02)

    # /api/jobs/active reports it.
    active = client.get("/api/jobs/active").json()["active"]
    assert active and active["id"] == jid and active["kind"] == "import"

    # Library-mutating endpoints are rejected with 409 while it runs.
    tree = client.get("/api/tree").json()
    album = tree["artists"][0]["children"][0]["path"]
    track = client.get("/api/album", params={"path": album}).json()["tracks"][0]["path"]
    assert client.post("/api/tags", json={"path": track, "updates": {"TIT2": "X"}}).status_code == 409
    assert client.post("/api/edit/apply",
                       json={"path": album, "op": "album_genre", "value": "Z"}).status_code == 409

    client.post(f"/api/jobs/{jid}/cancel")
    shutil.rmtree(src, ignore_errors=True)
