"""
Endpoint tests for the web UI (server.py).

The fixture builds a tiny real library in a tmp dir: a 1-second silent MP3
generated by ffmpeg and tagged with mutagen. A real MP3 matters — a fake-header
or zero-byte file makes browse._read_tags hit its except path and return {},
which would silently pass a broken read.
"""
import re
import shutil
import subprocess
import time
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

import server
from mutagen.id3 import ID3, TIT2, TPE1, TPE2, TALB, TYER, TRCK, TPOS, TCON

_FRAMES = {"TIT2": TIT2, "TPE1": TPE1, "TPE2": TPE2,
           "TALB": TALB, "TYER": TYER, "TRCK": TRCK, "TPOS": TPOS, "TCON": TCON}


def _make_mp3(path, **frames):
    """Create a real (ffmpeg) MP3 at *path* tagged with *frames* (defaults given)."""
    if not frames:
        frames = {"TIT2": "Silent Night", "TPE1": "Test Artist", "TPE2": "Test Artist",
                  "TALB": "Test Album", "TYER": "2024", "TRCK": "01/1"}
    path.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
         "-f", "lavfi", "-i", "anullsrc=r=44100:cl=stereo",
         "-t", "1", "-q:a", "9", str(path)],
        check=True,
    )
    tags = ID3()
    for fid, val in frames.items():
        tags.add(_FRAMES[fid](encoding=3, text=val))
    tags.save(path, v2_version=3, v1=0)


def _poll(client, jid, answer=None, max_iter=400):
    """Drive a job to a terminal state, answering prompts via answer(prompt)->value."""
    for _ in range(max_iter):
        j = client.get(f"/api/jobs/{jid}").json()
        if j["state"] == "waiting":
            val = answer(j["prompt"]) if answer else ""
            client.post(f"/api/jobs/{jid}/respond", json={"value": val})
        elif j["state"] in ("done", "error"):
            return j
        time.sleep(0.03)
    return client.get(f"/api/jobs/{jid}").json()


@pytest.fixture()
def client(tmp_path):
    if shutil.which("ffmpeg") is None:
        pytest.skip("ffmpeg not available")
    album = tmp_path / "Test Artist" / "2024 - Test Album"
    album.mkdir(parents=True)
    _make_mp3(album / "01. Test Artist - Silent Night.mp3")
    server.set_root(tmp_path)
    return TestClient(server.app)


def test_tree_shape(client):
    data = client.get("/api/tree").json()
    assert data["artists"], "expected at least one artist"
    artist = data["artists"][0]
    assert artist["kind"] == "artist"
    assert artist["label"] == "Test Artist"
    album = artist["children"][0]
    assert album["kind"] == "album"
    track = album["children"][0]
    assert track["kind"] == "track"
    assert track["path"].endswith(".mp3")


def test_album_reads_real_tags(client):
    tree = client.get("/api/tree").json()
    album_path = tree["artists"][0]["children"][0]["path"]
    data = client.get("/api/album", params={"path": album_path}).json()
    assert len(data["tracks"]) == 1
    t = data["tracks"][0]
    # A real MP3 must yield populated tags, not the {} except-path.
    assert t["title"] == "Silent Night"
    assert t["artist"] == "Test Artist"
    assert t["album"] == "Test Album"
    assert t["year"] == "2024"
    # Duration is exposed for the Time column (1-second fixture → "0:01").
    assert re.fullmatch(r"\d+:\d{2}", t["length"])


def test_tag_write_read_roundtrip(client):
    tree = client.get("/api/tree").json()
    album_path = tree["artists"][0]["children"][0]["path"]
    track_path = client.get("/api/album", params={"path": album_path}).json()["tracks"][0]["path"]

    resp = client.post("/api/tags", json={
        "path": track_path,
        "updates": {"TIT2": "Renamed Title", "TPE1": "Renamed Artist"},
    })
    assert resp.status_code == 200
    assert resp.json()["title"] == "Renamed Title"

    # Re-read independently to prove it persisted to disk.
    again = client.get("/api/album", params={"path": album_path}).json()["tracks"][0]
    assert again["title"] == "Renamed Title"
    assert again["artist"] == "Renamed Artist"


def test_safe_rejects_outside_root(client):
    resp = client.get("/api/album", params={"path": "/etc"})
    assert resp.status_code == 403


def test_track_streams_audio(client):
    tree = client.get("/api/tree").json()
    album = tree["artists"][0]["children"][0]["path"]
    track = client.get("/api/album", params={"path": album}).json()["tracks"][0]["path"]

    full = client.get("/api/track", params={"path": track})
    assert full.status_code == 200
    assert full.headers["content-type"] == "audio/mpeg"
    assert full.headers.get("accept-ranges") == "bytes"

    # Range request → 206 partial content (enables seeking).
    part = client.get("/api/track", params={"path": track}, headers={"Range": "bytes=0-99"})
    assert part.status_code == 206
    assert "content-range" in part.headers
    assert len(part.content) == 100


def test_track_rejects_outside_root(client):
    assert client.get("/api/track", params={"path": "/etc/passwd"}).status_code == 403


# ── Search ────────────────────────────────────────────────────────────────────

def test_search_finds_track(client):
    data = client.get("/api/search", params={"q": "silent"}).json()
    assert len(data["tracks"]) == 1
    t = data["tracks"][0]
    assert t["title"] == "Silent Night"
    assert t["path"].endswith("Silent Night.mp3")
    assert t["album_path"].endswith("2024 - Test Album")
    assert t["artist_path"].endswith("Test Artist")


def test_search_finds_album_case_insensitive(client):
    data = client.get("/api/search", params={"q": "TEST ALBUM"}).json()
    assert any(a["path"].endswith("2024 - Test Album") for a in data["albums"])


def test_search_empty_query(client):
    data = client.get("/api/search", params={"q": ""}).json()
    assert data == {"albums": [], "tracks": []}


# ── Local artwork upload ──────────────────────────────────────────────────────

def test_art_upload_local_file(client, tmp_path):
    pytest.importorskip("PIL")
    import io
    from PIL import Image
    buf = io.BytesIO()
    Image.new("RGB", (20, 20), (200, 30, 30)).save(buf, "PNG")

    tree = client.get("/api/tree").json()
    album = tree["artists"][0]["children"][0]["path"]
    resp = client.post("/api/art/upload", params={"path": album},
                       content=buf.getvalue(), headers={"Content-Type": "image/png"})
    assert resp.status_code == 200 and resp.json()["updated"] >= 1
    assert list(Path(album).glob("cover.*")), "expected a cover file written"


def test_art_upload_empty_rejected(client):
    tree = client.get("/api/tree").json()
    album = tree["artists"][0]["children"][0]["path"]
    resp = client.post("/api/art/upload", params={"path": album}, content=b"",
                       headers={"Content-Type": "image/png"})
    assert resp.status_code == 400


def test_settings_roundtrip(client):
    client.post("/api/settings", json={"cover_art": "both"})
    assert client.get("/api/settings").json()["cover_art"] == "both"


# ── Background image ──────────────────────────────────────────────────────────

def test_background_upload_serve_clear(client, tmp_path):
    # Initially absent.
    s = client.get("/api/settings").json()
    assert s["background_present"] is False and s["background_version"] == 0
    assert client.get("/api/background").status_code == 404

    # Upload raw image bytes.
    img = b"\x89PNG\r\n\x1a\nfake-image-bytes"
    up = client.post("/api/background", content=img, headers={"Content-Type": "image/png"})
    assert up.status_code == 200 and up.json()["version"] > 0
    assert (tmp_path / ".mp3tools-background").is_file()

    # Settings now report presence + version; image is served with its mime.
    s = client.get("/api/settings").json()
    assert s["background_present"] is True and s["background_version"] > 0
    got = client.get("/api/background")
    assert got.status_code == 200
    assert got.headers["content-type"] == "image/png"
    assert got.content == img

    # Clear removes file + mime, and serving 404s again.
    assert client.delete("/api/background").status_code == 200
    assert not (tmp_path / ".mp3tools-background").is_file()
    assert client.get("/api/settings").json()["background_present"] is False
    assert client.get("/api/background").status_code == 404


def test_background_empty_rejected(client):
    resp = client.post("/api/background", content=b"", headers={"Content-Type": "image/png"})
    assert resp.status_code == 400


def test_background_tunables_roundtrip(client):
    client.post("/api/settings", json={
        "background_opacity": 0.65, "background_blur": 12, "background_fit": "contain"})
    s = client.get("/api/settings").json()
    assert s["background_opacity"] == 0.65
    assert s["background_blur"] == 12
    assert s["background_fit"] == "contain"
    # Out-of-range / invalid values are clamped or ignored on load.
    client.post("/api/settings", json={
        "background_opacity": 5, "background_blur": 999, "background_fit": "bogus"})
    s = client.get("/api/settings").json()
    assert s["background_opacity"] == 1.0
    assert s["background_blur"] == 40
    assert s["background_fit"] == "cover"   # invalid value falls back to the default


# ── Structural edits ──────────────────────────────────────────────────────────

def test_edit_track_title_renames_file(client):
    tree = client.get("/api/tree").json()
    album_path = tree["artists"][0]["children"][0]["path"]
    track_path = client.get("/api/album", params={"path": album_path}).json()["tracks"][0]["path"]

    resp = client.post("/api/edit/apply",
                       json={"path": track_path, "op": "track_title", "value": "Brand New"})
    assert resp.status_code == 200 and resp.json()["ok"]

    again = client.get("/api/album", params={"path": album_path}).json()["tracks"][0]
    assert again["title"] == "Brand New"
    assert again["path"].endswith("Brand New.mp3")  # file was renamed


def test_edit_album_year_moves_folder(client, tmp_path):
    tree = client.get("/api/tree").json()
    album_path = tree["artists"][0]["children"][0]["path"]
    resp = client.post("/api/edit/apply",
                       json={"path": album_path, "op": "album_year", "value": "1999"})
    body = resp.json()
    assert body["ok"]
    # new_path reports the moved folder and it exists on disk.
    assert body["new_path"] != album_path
    assert body["new_path"].endswith("1999 - Test Album")
    from pathlib import Path
    assert Path(body["new_path"]).is_dir()
    artist_dir = tmp_path / "Test Artist"
    names = sorted(p.name for p in artist_dir.iterdir())
    assert any(n.startswith("1999 - ") for n in names)


def test_edit_album_genre_keeps_path(client):
    tree = client.get("/api/tree").json()
    album_path = tree["artists"][0]["children"][0]["path"]
    resp = client.post("/api/edit/apply",
                       json={"path": album_path, "op": "album_genre", "value": "Jazz"})
    body = resp.json()
    assert body["ok"]
    # genre is a tag-only edit — folder does not move.
    assert body["new_path"] == album_path


def test_album_reorder_renumbers_and_renames(client, tmp_path):
    album = tmp_path / "Reorder Artist" / "2024 - Reorder Album"
    _make_mp3(album / "01. Reorder Artist - One.mp3", TIT2="One", TPE1="Reorder Artist",
              TPE2="Reorder Artist", TALB="Reorder Album", TYER="2024", TRCK="01/3")
    _make_mp3(album / "02. Reorder Artist - Two.mp3", TIT2="Two", TPE1="Reorder Artist",
              TPE2="Reorder Artist", TALB="Reorder Album", TYER="2024", TRCK="02/3")
    _make_mp3(album / "03. Reorder Artist - Three.mp3", TIT2="Three", TPE1="Reorder Artist",
              TPE2="Reorder Artist", TALB="Reorder Album", TYER="2024", TRCK="03/3")

    # New order: Three, One, Two (a swap that would collide with naive renaming).
    order = [str(album / "03. Reorder Artist - Three.mp3"),
             str(album / "01. Reorder Artist - One.mp3"),
             str(album / "02. Reorder Artist - Two.mp3")]
    resp = client.post("/api/album/reorder", json={"path": str(album), "order": order})
    assert resp.status_code == 200 and resp.json()["ok"], resp.json()

    names = sorted(p.name for p in album.glob("*.mp3"))
    assert names == ["01. Reorder Artist - Three.mp3",
                     "02. Reorder Artist - One.mp3",
                     "03. Reorder Artist - Two.mp3"]
    t1 = ID3(album / "01. Reorder Artist - Three.mp3", translate=False)
    assert str(t1.get("TIT2")) == "Three" and str(t1.get("TRCK")) == "01/3"


def test_album_reorder_rejects_outside_album(client, tmp_path):
    tree = client.get("/api/tree").json()
    album = tree["artists"][0]["children"][0]["path"]
    resp = client.post("/api/album/reorder",
                       json={"path": album, "order": ["/etc/passwd"]})
    assert resp.status_code in (400, 403)


def test_import_merges_discs_in_order(tmp_path, tmp_path_factory):
    if shutil.which("ffmpeg") is None:
        pytest.skip("ffmpeg not available")
    src = tmp_path_factory.mktemp("multidisc")
    common = dict(TPE1="Band", TPE2="Band", TALB="Live", TYER="2003", TCON="Rock")
    _make_mp3(src / "CD2" / "a.mp3", TIT2="D2T1", TPOS="2/2", TRCK="1", **common)
    _make_mp3(src / "CD1" / "b.mp3", TIT2="D1T1", TPOS="1/2", TRCK="1", **common)
    server.set_root(tmp_path)
    c = TestClient(server.app)

    seen = {}

    def answer(prompt):
        if prompt["kind"] == "preview":
            # Both discs serialize with the same destination (one merged album).
            seen["n"] = len(prompt["entries"])
            return {"proceed": True, "entries": prompt["entries"]}
        if prompt["kind"] == "choice" and prompt["options"]:
            return prompt["options"][0]["key"]
        return ""

    jid = c.post("/api/jobs", json={"kind": "import", "source": str(src)}).json()["job_id"]
    assert _poll(c, jid, answer)["state"] == "done"
    dest = tmp_path / "Band" / "2003 - Live"
    names = sorted(p.name for p in dest.glob("*.mp3"))
    assert len(names) == 2
    # Disc 1 track numbered before disc 2 in the single merged album.
    assert ID3(dest / names[0], translate=False).get("TIT2").text[0] == "D1T1"
    assert ID3(dest / names[1], translate=False).get("TIT2").text[0] == "D2T1"


def test_import_order_honored(tmp_path, tmp_path_factory):
    if shutil.which("ffmpeg") is None:
        pytest.skip("ffmpeg not available")
    src = tmp_path_factory.mktemp("ordersrc")
    _make_mp3(src / "a.mp3", TIT2="Aaa", TPE1="Ord", TPE2="Ord", TALB="OrdAlbum",
              TYER="2020", TRCK="1")
    _make_mp3(src / "b.mp3", TIT2="Bbb", TPE1="Ord", TPE2="Ord", TALB="OrdAlbum",
              TYER="2020", TRCK="2")
    _make_mp3(src / "c.mp3", TIT2="Ccc", TPE1="Ord", TPE2="Ord", TALB="OrdAlbum",
              TYER="2020", TRCK="3")
    server.set_root(tmp_path)
    c = TestClient(server.app)

    # Submit in a known shuffled preview order: Ccc, Aaa, Bbb.
    submitted = ["Ccc", "Aaa", "Bbb"]

    def answer(prompt):
        if prompt["kind"] == "preview":
            rows = prompt["entries"]
            rows.sort(key=lambda r: submitted.index(r["title"]))
            return {"proceed": True, "entries": rows}
        if prompt["kind"] == "choice" and prompt["options"]:
            return prompt["options"][0]["key"]
        return ""

    jid = c.post("/api/jobs", json={"kind": "import", "source": str(src)}).json()["job_id"]
    assert _poll(c, jid, answer)["state"] == "done"
    dest = tmp_path / "Ord" / "2020 - OrdAlbum"
    # The on-disk track numbers must match the submitted (preview) order exactly.
    for n, title in enumerate(submitted, 1):
        f = dest / f"0{n}. Ord - {title}.mp3"
        assert f.is_file(), sorted(p.name for p in dest.glob("*.mp3"))
        assert str(ID3(f, translate=False).get("TRCK")) == f"0{n}/3"


def test_album_delete_and_prunes_artist(client, tmp_path):
    tree = client.get("/api/tree").json()
    album_path = tree["artists"][0]["children"][0]["path"]
    resp = client.post("/api/album/delete", json={"path": album_path})
    assert resp.status_code == 200 and resp.json()["ok"]
    assert not Path(album_path).exists()
    # It was the artist's only album → the empty artist folder is pruned.
    assert not (tmp_path / "Test Artist").exists()


def test_album_delete_rejects_artist_dir(client, tmp_path):
    # An artist-level path (parent == ROOT) must not be deletable.
    resp = client.post("/api/album/delete", json={"path": str(tmp_path / "Test Artist")})
    assert resp.status_code == 400
    assert (tmp_path / "Test Artist").is_dir()


def test_album_delete_rejects_outside_root(client):
    assert client.post("/api/album/delete", json={"path": "/etc"}).status_code == 403


def test_edit_unknown_op_400(client):
    tree = client.get("/api/tree").json()
    album_path = tree["artists"][0]["children"][0]["path"]
    resp = client.post("/api/edit/apply",
                       json={"path": album_path, "op": "bogus", "value": "x"})
    assert resp.status_code == 400


# ── Audit ─────────────────────────────────────────────────────────────────────

def test_audit_returns_categories(client):
    data = client.get("/api/audit").json()
    assert "category_labels" in data and data["category_labels"]
    assert set(data["totals"]) == {"albums", "albums_with_issues", "files", "files_with_issues"}


# ── Jobs ──────────────────────────────────────────────────────────────────────

def test_standardize_dry_run_job(client):
    jid = client.post("/api/jobs", json={"kind": "standardize", "dry_run": True}).json()["job_id"]
    j = _poll(client, jid)
    assert j["state"] == "done", j.get("error")
    assert j["log"], "expected captured log output"


def test_standardize_prompt_roundtrip(tmp_path):
    if shutil.which("ffmpeg") is None:
        pytest.skip("ffmpeg not available")
    # A file missing TIT2 forces step 2 (fix missing tags) to prompt.
    album = tmp_path / "Artist" / "2024 - Album"
    _make_mp3(album / "01. Artist - Track.mp3",
              TPE1="Artist", TPE2="Artist", TALB="Album", TYER="2024", TRCK="01/1")
    server.set_root(tmp_path)
    c = TestClient(server.app)

    asked = []

    def answer(prompt):
        asked.append(prompt["kind"])
        if prompt["kind"] == "text" and "Title" in prompt["prompt"]:
            return "Filled In"
        if prompt["kind"] == "choice" and prompt["options"]:
            return prompt["options"][0]["key"]
        return ""

    jid = c.post("/api/jobs", json={"kind": "standardize", "dry_run": False}).json()["job_id"]
    j = _poll(c, jid, answer)
    assert j["state"] == "done", j.get("error")
    assert "text" in asked, "expected at least one text prompt"
    # The title we supplied should now be on disk (file likely renamed to match).
    written = list((tmp_path / "Artist").rglob("*.mp3"))
    assert written
    tags = ID3(written[0], translate=False)
    assert str(tags.get("TIT2")) == "Filled In"


def test_import_job_copies_file(tmp_path, tmp_path_factory):
    if shutil.which("ffmpeg") is None:
        pytest.skip("ffmpeg not available")
    src = tmp_path_factory.mktemp("source")
    _make_mp3(src / "song.mp3", TIT2="Imported", TPE1="Imp", TPE2="Imp",
              TALB="ImpAlbum", TYER="2020", TRCK="1")
    server.set_root(tmp_path)
    c = TestClient(server.app)

    def answer(prompt):
        if prompt["kind"] == "preview":
            return {"proceed": True, "entries": prompt["entries"]}
        if prompt["kind"] == "choice" and prompt["options"]:
            return prompt["options"][0]["key"]
        return ""

    jid = c.post("/api/jobs",
                 json={"kind": "import", "source": str(src), "dry_run": False}).json()["job_id"]
    j = _poll(c, jid, answer)
    assert j["state"] == "done", j.get("error")
    imported = list(tmp_path.rglob("*.mp3"))
    assert imported, "expected an imported file in the library"


def test_import_via_upload(tmp_path, tmp_path_factory):
    if shutil.which("ffmpeg") is None:
        pytest.skip("ffmpeg not available")
    # Build a real MP3 on disk, then upload its bytes through the drag-drop endpoints.
    staging = tmp_path_factory.mktemp("staging")
    _make_mp3(staging / "song.mp3", TIT2="Dropped", TPE1="Dee", TPE2="Dee",
              TALB="DropAlbum", TYER="2021", TRCK="1")
    server.set_root(tmp_path)
    c = TestClient(server.app)

    token = c.post("/api/import/upload/start").json()["token"]
    upload_dir = server._UPLOADS[token]
    up = c.post("/api/import/upload/file",
                params={"token": token, "path": "DropAlbum/song.mp3"},
                content=(staging / "song.mp3").read_bytes(),
                headers={"Content-Type": "audio/mpeg"})
    assert up.status_code == 200
    assert (upload_dir / "DropAlbum" / "song.mp3").is_file()

    def answer(prompt):
        if prompt["kind"] == "preview":
            return {"proceed": True, "entries": prompt["entries"]}
        if prompt["kind"] == "choice" and prompt["options"]:
            return prompt["options"][0]["key"]
        return ""

    jid = c.post("/api/jobs",
                 json={"kind": "import", "upload_token": token}).json()["job_id"]
    j = _poll(c, jid, answer)
    assert j["state"] == "done", j.get("error")
    assert list(tmp_path.rglob("*.mp3")), "expected an imported file in the library"
    assert not upload_dir.exists(), "temp upload dir should be cleaned up after import"


def test_import_preview_edits_genre(tmp_path, tmp_path_factory):
    if shutil.which("ffmpeg") is None:
        pytest.skip("ffmpeg not available")
    src = tmp_path_factory.mktemp("source")
    _make_mp3(src / "song.mp3", TIT2="Tune", TPE1="Band", TPE2="Band",
              TALB="Rec", TYER="2022", TRCK="1")
    server.set_root(tmp_path)
    c = TestClient(server.app)

    def answer(prompt):
        if prompt["kind"] == "preview":
            entries = prompt["entries"]
            assert "genre" in entries[0]            # genre round-trips
            for e in entries:
                e["genre"] = "Jazz"
            return {"proceed": True, "entries": entries}
        if prompt["kind"] == "choice" and prompt["options"]:
            return prompt["options"][0]["key"]
        return ""

    jid = c.post("/api/jobs",
                 json={"kind": "import", "source": str(src)}).json()["job_id"]
    j = _poll(c, jid, answer)
    assert j["state"] == "done", j.get("error")
    imported = list(tmp_path.rglob("*.mp3"))
    assert imported
    assert str(ID3(imported[0], translate=False).get("TCON")) == "Jazz"


def _make_flac(path, **frames):
    path.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        ["ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
         "-f", "lavfi", "-i", "anullsrc=r=44100:cl=stereo", "-t", "1", str(path)],
        check=True,
    )
    if frames:
        from mutagen.flac import FLAC
        f = FLAC(path)
        for k, v in frames.items():
            f[k] = v
        f.save()


def test_import_preview_serializes_new_fields(tmp_path, tmp_path_factory):
    if shutil.which("ffmpeg") is None:
        pytest.skip("ffmpeg not available")
    src = tmp_path_factory.mktemp("source")
    _make_mp3(src / "song.mp3", TIT2="T", TPE1="A", TPE2="A", TALB="Al", TYER="2020", TRCK="1")
    server.set_root(tmp_path)
    c = TestClient(server.app)

    seen = {}

    def answer(prompt):
        if prompt["kind"] == "preview":
            seen["default_bitrate"] = prompt.get("default_bitrate")
            seen["row0"] = prompt["entries"][0]
            return {"proceed": True, "entries": prompt["entries"]}
        if prompt["kind"] == "choice" and prompt["options"]:
            return prompt["options"][0]["key"]
        return ""

    jid = c.post("/api/jobs", json={"kind": "import", "source": str(src)}).json()["job_id"]
    assert _poll(c, jid, answer)["state"] == "done"
    assert seen["default_bitrate"] == 320
    assert seen["row0"]["lossless"] is False
    assert "conflict" in seen["row0"]


def test_import_conflict_skip_and_add(tmp_path, tmp_path_factory):
    if shutil.which("ffmpeg") is None:
        pytest.skip("ffmpeg not available")
    # Pre-existing album in the library (dest derived from tags: Imp / 2020 - ImpAlbum).
    dest = tmp_path / "Imp" / "2020 - ImpAlbum"
    _make_mp3(dest / "01. Imp - Old.mp3", TIT2="Old", TPE1="Imp", TPE2="Imp",
              TALB="ImpAlbum", TYER="2020", TRCK="01/1")
    server.set_root(tmp_path)
    c = TestClient(server.app)

    def run(resolution):
        src = tmp_path_factory.mktemp("src")
        _make_mp3(src / "new.mp3", TIT2="New", TPE1="Imp", TPE2="Imp",
                  TALB="ImpAlbum", TYER="2020", TRCK="1")

        def answer(prompt):
            if prompt["kind"] == "preview":
                rows = prompt["entries"]
                assert rows[0]["conflict"] is True       # dest already exists
                for r in rows:
                    r["conflict"] = resolution
                return {"proceed": True, "entries": rows}
            if prompt["kind"] == "choice" and prompt["options"]:
                return prompt["options"][0]["key"]
            return ""

        jid = c.post("/api/jobs", json={"kind": "import", "source": str(src)}).json()["job_id"]
        assert _poll(c, jid, answer)["state"] == "done"

    run("skip")
    assert len(list(dest.glob("*.mp3"))) == 1           # skipped: untouched
    run("add")
    assert len(list(dest.glob("*.mp3"))) == 2           # added: appended


def test_import_lossless_bitrate_not_dropped(tmp_path, tmp_path_factory):
    if shutil.which("ffmpeg") is None:
        pytest.skip("ffmpeg not available")
    src = tmp_path_factory.mktemp("flacsrc")
    _make_flac(src / "track.flac", title="Song", artist="Band",
               albumartist="Band", album="FlacAlbum", date="2019", tracknumber="1")
    server.set_root(tmp_path)
    c = TestClient(server.app)

    def answer(prompt):
        if prompt["kind"] == "preview":
            rows = prompt["entries"]
            assert rows[0]["lossless"] is True
            for r in rows:
                r["bitrate"] = 128
            return {"proceed": True, "entries": rows}
        if prompt["kind"] == "choice" and prompt["options"]:
            return prompt["options"][0]["key"]
        return ""

    jid = c.post("/api/jobs", json={"kind": "import", "source": str(src)}).json()["job_id"]
    assert _poll(c, jid, answer)["state"] == "done"
    imported = list(tmp_path.rglob("*.mp3"))
    assert imported, "lossless entry must import (not be dropped) when a bitrate is set"


def test_import_art_none_writes_placeholder(tmp_path, tmp_path_factory):
    if shutil.which("ffmpeg") is None:
        pytest.skip("ffmpeg not available")
    pytest.importorskip("PIL")
    src = tmp_path_factory.mktemp("noart")
    _make_mp3(src / "song.mp3", TIT2="T", TPE1="Solo", TPE2="Solo",
              TALB="NoArt", TYER="2020", TRCK="1")
    server.set_root(tmp_path)
    c = TestClient(server.app)

    def answer(prompt):
        if prompt["kind"] == "preview":
            rows = prompt["entries"]
            for r in rows:
                r["art_none"] = True
            return {"proceed": True, "entries": rows}
        if prompt["kind"] == "choice" and prompt["options"]:
            return prompt["options"][0]["key"]
        return ""

    jid = c.post("/api/jobs", json={"kind": "import", "source": str(src)}).json()["job_id"]
    assert _poll(c, jid, answer)["state"] == "done"
    assert (tmp_path / "Solo" / "2020 - NoArt" / "cover.jpg").is_file()


def test_import_upload_rejects_traversal(client):
    token = client.post("/api/import/upload/start").json()["token"]
    resp = client.post("/api/import/upload/file",
                       params={"token": token, "path": "../evil.mp3"},
                       content=b"x", headers={"Content-Type": "audio/mpeg"})
    assert resp.status_code == 400


def test_import_cover_endpoint(client, tmp_path, monkeypatch):
    src = tmp_path / "incoming" / "Album"
    src.mkdir(parents=True)
    (src / "cover.jpg").write_bytes(b"\xff\xd8\xff\xe0jpegdata")
    # No active import → 404.
    monkeypatch.setattr(server, "_IMPORT_SOURCE", None)
    assert client.get("/api/import/cover", params={"path": str(src)}).status_code == 404
    # Bounded to the import source.
    monkeypatch.setattr(server, "_IMPORT_SOURCE", tmp_path / "incoming")
    ok = client.get("/api/import/cover", params={"path": str(src)})
    assert ok.status_code == 200 and ok.content == b"\xff\xd8\xff\xe0jpegdata"
    # Outside the source → 403.
    assert client.get("/api/import/cover", params={"path": "/etc"}).status_code == 403


def test_import_upload_unknown_token(client):
    resp = client.post("/api/import/upload/file",
                       params={"token": "nope", "path": "a.mp3"},
                       content=b"x")
    assert resp.status_code == 404


def test_second_job_conflict(client):
    # Start an import that will block on the preview prompt, then a second start -> 409.
    # Use a source with one file so it reaches the preview and waits.
    import tempfile
    src = tempfile.mkdtemp()
    _make_mp3(__import__("pathlib").Path(src) / "s.mp3",
              TIT2="A", TPE1="B", TPE2="B", TALB="C", TYER="2020", TRCK="1")
    first = client.post("/api/jobs", json={"kind": "import", "source": src}).json()["job_id"]
    # wait until it is waiting on preview
    for _ in range(200):
        if client.get(f"/api/jobs/{first}").json()["state"] == "waiting":
            break
        time.sleep(0.02)
    resp = client.post("/api/jobs", json={"kind": "standardize", "dry_run": True})
    assert resp.status_code == 409
    client.post(f"/api/jobs/{first}/cancel")  # release
    shutil.rmtree(src, ignore_errors=True)


# ── Sync ──────────────────────────────────────────────────────────────────────

def _sync_client(tmp_path):
    if shutil.which("ffmpeg") is None:
        pytest.skip("ffmpeg not available")
    _make_mp3(tmp_path / "Artist One" / "2019 - First" / "01. A - S.mp3")
    _make_mp3(tmp_path / "Artist One" / "2021 - Second" / "01. A - S.mp3")
    _make_mp3(tmp_path / "Artist Two" / "2020 - Solo" / "01. A - S.mp3")
    server.set_root(tmp_path)
    return TestClient(server.app)


def test_sync_artists_and_albums(tmp_path, tmp_path_factory):
    c = _sync_client(tmp_path)
    dev = tmp_path_factory.mktemp("device")
    data = c.get("/api/sync/artists", params={"device": str(dev)}).json()
    names = sorted(a["name"] for a in data["artists"])
    assert names == ["Artist One", "Artist Two"]
    assert all(a["status"] == "not on device" for a in data["artists"])

    albums = c.get("/api/sync/albums",
                   params={"artist": str(tmp_path / "Artist One"), "device": str(dev)}).json()
    assert albums["has_albums"]
    assert sorted(x["name"] for x in albums["albums"]) == ["2019 - First", "2021 - Second"]


def test_sync_plan_and_job_copies(tmp_path, tmp_path_factory):
    c = _sync_client(tmp_path)
    dev = tmp_path_factory.mktemp("device")
    selection = {
        str(tmp_path / "Artist One"): "all",
        str(tmp_path / "Artist Two"): [str(tmp_path / "Artist Two" / "2020 - Solo")],
    }
    plan = c.post("/api/sync/plan", json={"device": str(dev), "selection": selection}).json()
    assert plan["copy_files"] == 3 and plan["enough_space"]

    jid = c.post("/api/jobs",
                 json={"kind": "sync", "device": str(dev), "selection": selection}).json()["job_id"]
    j = _poll(c, jid)
    assert j["state"] == "done", j.get("error")
    copied = sorted(str(p.relative_to(dev)) for p in dev.rglob("*.mp3"))
    assert copied == [
        "Artist One/2019 - First/01. A - S.mp3",
        "Artist One/2021 - Second/01. A - S.mp3",
        "Artist Two/2020 - Solo/01. A - S.mp3",
    ]


def test_sync_device_inside_library_rejected(tmp_path):
    c = _sync_client(tmp_path)
    resp = c.get("/api/sync/artists", params={"device": str(tmp_path / "Artist One")})
    assert resp.status_code == 400


def test_sync_eta_helper():
    from webjobs import _eta, _fmt_duration
    assert _fmt_duration(95) == "1:35"
    assert _fmt_duration(3725) == "1:02:05"
    assert _eta(0, 100, 10) == ""          # nothing copied yet
    assert _eta(100, 100, 10) == ""        # finished
    assert _eta(50, 100, 0.2) == ""        # too early to estimate
    assert _eta(50, 100, 1.0) == " · ETA 0:01"   # half done in 1s → ~1s left


def test_sync_devices_endpoint(client):
    data = client.get("/api/sync/devices").json()
    assert "devices" in data and isinstance(data["devices"], list)


def test_device_rows_excludes_library(tmp_path, monkeypatch):
    import sync_library
    inside = tmp_path / "Artist"
    inside.mkdir()
    fake = [
        {"path": tmp_path, "free": 1, "total": 2},                 # the library itself
        {"path": inside, "free": 1, "total": 2},                   # inside the library
        {"path": Path("/run/media/x/USB"), "free": 100, "total": 200},
    ]
    monkeypatch.setattr(sync_library, "detect_devices", lambda: fake)
    rows = sync_library.device_rows(exclude=tmp_path)
    paths = [r["path"] for r in rows]
    assert str(tmp_path) not in paths
    assert str(inside) not in paths
    assert "/run/media/x/USB" in paths
    assert rows[0]["name"] == "USB" and rows[0]["free_h"]
    assert rows[0]["type"] == "generic"   # no "type" in the fake → defaulted


def test_device_rows_passes_type(tmp_path, monkeypatch):
    import sync_library
    monkeypatch.setattr(sync_library, "detect_devices",
                        lambda: [{"path": Path("/run/media/x/SD"), "free": 1,
                                  "total": 2, "type": "sd"}])
    rows = sync_library.device_rows()
    assert rows[0]["type"] == "sd"


def test_partition_base():
    from sync_library import _partition_base
    assert _partition_base("/dev/sdb1") == "sdb"
    assert _partition_base("/dev/mmcblk0p1") == "mmcblk0"
    assert _partition_base("/dev/nvme0n1p1") == "nvme0n1"


def test_classify_device(tmp_path):
    from sync_library import classify_device
    sysblock = tmp_path / "block"
    for name, removable in (("sdb", "1"), ("sda", "0")):
        (sysblock / name).mkdir(parents=True)
        (sysblock / name / "removable").write_text(removable + "\n")
    assert classify_device("/dev/mmcblk0p1", sysblock) == "sd"
    assert classify_device("/dev/sdb1", sysblock) == "usb"      # removable
    assert classify_device("/dev/sda1", sysblock) == "drive"    # fixed
    assert classify_device("/dev/nvme0n1p1", sysblock) == "drive"
    assert classify_device("/dev/mapper/luks-abc", sysblock) == "drive"   # LUKS/LVM
    assert classify_device(None, sysblock) == "generic"
    assert classify_device("//phone:mtp", sysblock) == "generic"


def test_is_syncable_mount():
    from sync_library import _is_syncable_mount
    assert _is_syncable_mount("/media/u/CARD", "vfat")
    assert _is_syncable_mount("/mnt/usb", "ext4")
    assert not _is_syncable_mount("/", "ext4")
    assert not _is_syncable_mount("/boot/efi", "vfat")
    assert not _is_syncable_mount("/boot", "ext4")
    assert not _is_syncable_mount("/mnt/dvd", "iso9660")
    assert not _is_syncable_mount("/tmp", "tmpfs")
    assert not _is_syncable_mount("/sys/fs/cgroup", "cgroup2")
    # /run/media devices are excluded from the /proc/mounts loop (the /run prefix)
    # and instead enumerated via the _DEVICE_BASES scan.
    assert not _is_syncable_mount("/run/media/u/USB", "ext4")


def test_edits_blocked_while_job_active(client, tmp_path):
    # Start an import that parks on the preview prompt, so a job is "active".
    import tempfile
    src = tempfile.mkdtemp()
    _make_mp3(Path(src) / "s.mp3", TIT2="A", TPE1="B", TPE2="B",
              TALB="C", TYER="2020", TRCK="1")
    jid = client.post("/api/jobs", json={"kind": "import", "source": src}).json()["job_id"]
    for _ in range(200):
        if client.get(f"/api/jobs/{jid}").json()["state"] == "waiting":
            break
        time.sleep(0.02)

    # /api/jobs/active reports it.
    active = client.get("/api/jobs/active").json()["active"]
    assert active and active["id"] == jid and active["kind"] == "import"

    # Library-mutating endpoints are rejected with 409 while it runs.
    tree = client.get("/api/tree").json()
    album = tree["artists"][0]["children"][0]["path"]
    track = client.get("/api/album", params={"path": album}).json()["tracks"][0]["path"]
    assert client.post("/api/tags", json={"path": track, "updates": {"TIT2": "X"}}).status_code == 409
    assert client.post("/api/edit/apply",
                       json={"path": album, "op": "album_genre", "value": "Z"}).status_code == 409

    client.post(f"/api/jobs/{jid}/cancel")
    shutil.rmtree(src, ignore_errors=True)


# ── Album-art matching (edition-tolerant + fuzzy) ─────────────────────────────

def test_strip_edition():
    from fetch_art import _strip_edition
    assert _strip_edition("Album (Deluxe Edition)") == "Album"
    assert _strip_edition("Album [Remastered]") == "Album"
    assert _strip_edition("Album - Remastered 2011") == "Album"
    assert _strip_edition("Album (Disc 2)") == "Album"
    assert _strip_edition("Album") == "Album"                 # unchanged
    assert _strip_edition("(Deluxe Edition)") == "(Deluxe Edition)"  # don't empty it


def test_match_score_edition_tolerant():
    from fetch_art import _match_score, CONFIDENT_MATCH_SCORE
    # Deluxe-vs-plain (artist exact) still clears the confident bar.
    assert _match_score("Artist", "Album", "Artist", "Album (Deluxe Edition)") \
        >= CONFIDENT_MATCH_SCORE
    assert _match_score("Artist", "Album (Deluxe Edition)", "Artist", "Album") \
        >= CONFIDENT_MATCH_SCORE
    # A small typo still scores via the fuzzy fallback, above a clearly different album.
    typo = _match_score("Artist", "Album", "Artist", "Albbum")
    other = _match_score("Artist", "Album", "Artist", "Completely Different")
    assert typo > other
