"""
Endpoint tests for the web UI (server.py).

The fixture builds a tiny real library in a tmp dir: a 1-second silent MP3
generated by ffmpeg and tagged with mutagen. A real MP3 matters — a fake-header
or zero-byte file makes browse._read_tags hit its except path and return {},
which would silently pass a broken read.
"""
import re
import shutil
import time
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

import server
from mutagen.id3 import ID3

from conftest import make_flac as _make_flac, make_mp3 as _make_mp3, poll as _poll

pytestmark = pytest.mark.ffmpeg


@pytest.fixture()
def client(tmp_path):
    album = tmp_path / "Test Artist" / "2024 - Test Album"
    album.mkdir(parents=True)
    _make_mp3(album / "01. Test Artist - Silent Night.mp3")
    server.set_root(tmp_path)
    # Default client is the loopback owner (full access); TestClient otherwise
    # reports host "testclient", which the guest gate would treat as read-only.
    return TestClient(server.app, client=("127.0.0.1", 12345))


@pytest.fixture()
def guest(client):
    """A read-only client from a non-loopback (LAN) address."""
    return TestClient(server.app, client=("192.168.1.50", 12345))


def test_tree_shape(client):
    data = client.get("/api/tree").json()
    assert data["artists"], "expected at least one artist"
    artist = data["artists"][0]
    assert artist["kind"] == "artist"
    assert artist["label"] == "Test Artist"
    album = artist["children"][0]
    assert album["kind"] == "album"
    track = album["children"][0]
    assert track["kind"] == "track"
    assert track["path"].endswith(".mp3")


def test_album_reads_real_tags(client):
    tree = client.get("/api/tree").json()
    album_path = tree["artists"][0]["children"][0]["path"]
    data = client.get("/api/album", params={"path": album_path}).json()
    assert len(data["tracks"]) == 1
    t = data["tracks"][0]
    # A real MP3 must yield populated tags, not the {} except-path.
    assert t["title"] == "Silent Night"
    assert t["artist"] == "Test Artist"
    assert t["album"] == "Test Album"
    assert t["year"] == "2024"
    # Duration is exposed for the Time column (1-second fixture → "0:01").
    assert re.fullmatch(r"\d+:\d{2}", t["length"])


def test_tag_write_read_roundtrip(client):
    tree = client.get("/api/tree").json()
    album_path = tree["artists"][0]["children"][0]["path"]
    track_path = client.get("/api/album", params={"path": album_path}).json()["tracks"][0]["path"]

    resp = client.post("/api/tags", json={
        "path": track_path,
        "updates": {"TIT2": "Renamed Title", "TPE1": "Renamed Artist"},
    })
    assert resp.status_code == 200
    assert resp.json()["title"] == "Renamed Title"

    # Re-read independently to prove it persisted to disk.
    again = client.get("/api/album", params={"path": album_path}).json()["tracks"][0]
    assert again["title"] == "Renamed Title"
    assert again["artist"] == "Renamed Artist"


def test_safe_rejects_outside_root(client):
    resp = client.get("/api/album", params={"path": "/etc"})
    assert resp.status_code == 403


def test_track_streams_audio(client):
    tree = client.get("/api/tree").json()
    album = tree["artists"][0]["children"][0]["path"]
    track = client.get("/api/album", params={"path": album}).json()["tracks"][0]["path"]

    full = client.get("/api/track", params={"path": track})
    assert full.status_code == 200
    assert full.headers["content-type"] == "audio/mpeg"
    assert full.headers.get("accept-ranges") == "bytes"

    # Range request → 206 partial content (enables seeking).
    part = client.get("/api/track", params={"path": track}, headers={"Range": "bytes=0-99"})
    assert part.status_code == 206
    assert "content-range" in part.headers
    assert len(part.content) == 100


def test_track_rejects_outside_root(client):
    assert client.get("/api/track", params={"path": "/etc/passwd"}).status_code == 403


# ── Search ────────────────────────────────────────────────────────────────────

def test_search_finds_track(client):
    data = client.get("/api/search", params={"q": "silent"}).json()
    assert len(data["tracks"]) == 1
    t = data["tracks"][0]
    assert t["title"] == "Silent Night"
    assert t["path"].endswith("Silent Night.mp3")
    assert t["album_path"].endswith("2024 - Test Album")
    assert t["artist_path"].endswith("Test Artist")


def test_search_finds_album_case_insensitive(client):
    data = client.get("/api/search", params={"q": "TEST ALBUM"}).json()
    assert any(a["path"].endswith("2024 - Test Album") for a in data["albums"])


def test_search_finds_artist(client):
    data = client.get("/api/search", params={"q": "test artist"}).json()
    assert any(a["artist_path"].endswith("Test Artist") for a in data["artists"])
    match = next(a for a in data["artists"] if a["artist_path"].endswith("Test Artist"))
    assert match["artist"] == "Test Artist"
    assert match["n_albums"] >= 1


def test_search_empty_query(client):
    data = client.get("/api/search", params={"q": ""}).json()
    assert data == {"artists": [], "albums": [], "tracks": []}


def test_genre_lists_albums(client, tmp_path):
    # Two albums (different artists) tagged Rock, plus one tagged Jazz.
    _make_mp3(tmp_path / "Rocker" / "2001 - Loud" / "01. Rocker - A.mp3",
              TIT2="A", TPE1="Rocker", TPE2="Rocker", TALB="Loud", TYER="2001",
              TRCK="01/1", TCON="Rock")
    _make_mp3(tmp_path / "Stoner" / "2010 - Heavy" / "01. Stoner - B.mp3",
              TIT2="B", TPE1="Stoner", TPE2="Stoner", TALB="Heavy", TYER="2010",
              TRCK="01/1", TCON="rock")          # case-insensitive match
    _make_mp3(tmp_path / "Smooth" / "2005 - Mellow" / "01. Smooth - C.mp3",
              TIT2="C", TPE1="Smooth", TPE2="Smooth", TALB="Mellow", TYER="2005",
              TRCK="01/1", TCON="Jazz")

    data = client.get("/api/genre", params={"name": "Rock"}).json()
    assert data["genre"] == "Rock"
    albums = data["albums"]
    titles = sorted(a["album"] for a in albums)
    assert titles == ["Heavy", "Loud"]
    loud = next(a for a in albums if a["album"] == "Loud")
    assert loud["album_path"].endswith("2001 - Loud")
    assert loud["artist_path"].endswith("Rocker")
    assert loud["year"] == "2001"


def test_genre_empty(client):
    data = client.get("/api/genre", params={"name": "Nonexistent"}).json()
    assert data == {"genre": "Nonexistent", "albums": []}


# ── Local artwork upload ──────────────────────────────────────────────────────

def test_art_upload_local_file(client, tmp_path):
    pytest.importorskip("PIL")
    import io
    from PIL import Image
    buf = io.BytesIO()
    Image.new("RGB", (20, 20), (200, 30, 30)).save(buf, "PNG")

    tree = client.get("/api/tree").json()
    album = tree["artists"][0]["children"][0]["path"]
    resp = client.post("/api/art/upload", params={"path": album},
                       content=buf.getvalue(), headers={"Content-Type": "image/png"})
    assert resp.status_code == 200 and resp.json()["updated"] >= 1
    assert list(Path(album).glob("cover.*")), "expected a cover file written"


def test_art_upload_empty_rejected(client):
    tree = client.get("/api/tree").json()
    album = tree["artists"][0]["children"][0]["path"]
    resp = client.post("/api/art/upload", params={"path": album}, content=b"",
                       headers={"Content-Type": "image/png"})
    assert resp.status_code == 400


def test_art_thumb_proxies_image(client, monkeypatch):
    import fetch_art
    monkeypatch.setattr(fetch_art, "fetch_artwork",
                        lambda url: (b"\xff\xd8fakejpeg", "image/jpeg"))
    resp = client.get("/api/art/thumb", params={"url": "https://example.com/a.jpg"})
    assert resp.status_code == 200
    assert resp.content == b"\xff\xd8fakejpeg"
    assert resp.headers["content-type"] == "image/jpeg"


def test_art_thumb_rejects_non_http(client):
    resp = client.get("/api/art/thumb", params={"url": "file:///etc/passwd"})
    assert resp.status_code == 400


def test_art_apply_rejects_non_http(client):
    tree = client.get("/api/tree").json()
    album = tree["artists"][0]["children"][0]["path"]
    resp = client.post("/api/art/apply",
                       json={"path": album, "url": "file:///etc/passwd"})
    assert resp.status_code == 400


def test_settings_roundtrip(client):
    client.post("/api/settings", json={"cover_art": "both"})
    assert client.get("/api/settings").json()["cover_art"] == "both"


def test_theme_accent_setting(client):
    assert client.get("/api/settings").json()["theme_accent_from_art"] is False
    client.post("/api/settings", json={"theme_accent_from_art": True})
    assert client.get("/api/settings").json()["theme_accent_from_art"] is True
    client.post("/api/settings", json={"theme_accent_from_art": False})
    assert client.get("/api/settings").json()["theme_accent_from_art"] is False
    # A non-bool fails validation on load and falls back to the default (False).
    client.post("/api/settings", json={"theme_accent_from_art": "yes"})
    assert client.get("/api/settings").json()["theme_accent_from_art"] is False


# ── Background image ──────────────────────────────────────────────────────────

def test_background_upload_serve_clear(client, tmp_path):
    # Initially absent.
    s = client.get("/api/settings").json()
    assert s["background_present"] is False and s["background_version"] == 0
    assert client.get("/api/background").status_code == 404

    # Upload raw image bytes.
    img = b"\x89PNG\r\n\x1a\nfake-image-bytes"
    up = client.post("/api/background", content=img, headers={"Content-Type": "image/png"})
    assert up.status_code == 200 and up.json()["version"] > 0
    assert (tmp_path / ".mp3tools" / "background").is_file()

    # Settings now report presence + version; image is served with its mime.
    s = client.get("/api/settings").json()
    assert s["background_present"] is True and s["background_version"] > 0
    got = client.get("/api/background")
    assert got.status_code == 200
    assert got.headers["content-type"] == "image/png"
    assert got.content == img

    # Clear removes file + mime, and serving 404s again.
    assert client.delete("/api/background").status_code == 200
    assert not (tmp_path / ".mp3tools" / "background").is_file()
    assert client.get("/api/settings").json()["background_present"] is False
    assert client.get("/api/background").status_code == 404


def test_background_empty_rejected(client):
    resp = client.post("/api/background", content=b"", headers={"Content-Type": "image/png"})
    assert resp.status_code == 400


def test_background_tunables_roundtrip(client):
    client.post("/api/settings", json={
        "background_opacity": 0.65, "background_blur": 12, "background_fit": "contain"})
    s = client.get("/api/settings").json()
    assert s["background_opacity"] == 0.65
    assert s["background_blur"] == 12
    assert s["background_fit"] == "contain"
    # Out-of-range / invalid values are clamped or ignored on load.
    client.post("/api/settings", json={
        "background_opacity": 5, "background_blur": 999, "background_fit": "bogus"})
    s = client.get("/api/settings").json()
    assert s["background_opacity"] == 1.0
    assert s["background_blur"] == 40
    assert s["background_fit"] == "cover"   # invalid value falls back to the default


# ── Structural edits ──────────────────────────────────────────────────────────

def test_edit_track_title_renames_file(client):
    tree = client.get("/api/tree").json()
    album_path = tree["artists"][0]["children"][0]["path"]
    track_path = client.get("/api/album", params={"path": album_path}).json()["tracks"][0]["path"]

    resp = client.post("/api/edit/apply",
                       json={"path": track_path, "op": "track_title", "value": "Brand New"})
    assert resp.status_code == 200 and resp.json()["ok"]

    again = client.get("/api/album", params={"path": album_path}).json()["tracks"][0]
    assert again["title"] == "Brand New"
    assert again["path"].endswith("Brand New.mp3")  # file was renamed


def test_edit_album_year_moves_folder(client, tmp_path):
    tree = client.get("/api/tree").json()
    album_path = tree["artists"][0]["children"][0]["path"]
    resp = client.post("/api/edit/apply",
                       json={"path": album_path, "op": "album_year", "value": "1999"})
    body = resp.json()
    assert body["ok"]
    # new_path reports the moved folder and it exists on disk.
    assert body["new_path"] != album_path
    assert body["new_path"].endswith("1999 - Test Album")
    from pathlib import Path
    assert Path(body["new_path"]).is_dir()
    artist_dir = tmp_path / "Test Artist"
    names = sorted(p.name for p in artist_dir.iterdir())
    assert any(n.startswith("1999 - ") for n in names)


def test_edit_album_genre_keeps_path(client):
    tree = client.get("/api/tree").json()
    album_path = tree["artists"][0]["children"][0]["path"]
    resp = client.post("/api/edit/apply",
                       json={"path": album_path, "op": "album_genre", "value": "Jazz"})
    body = resp.json()
    assert body["ok"]
    # genre is a tag-only edit — folder does not move.
    assert body["new_path"] == album_path


def test_album_reorder_renumbers_and_renames(client, tmp_path):
    album = tmp_path / "Reorder Artist" / "2024 - Reorder Album"
    _make_mp3(album / "01. Reorder Artist - One.mp3", TIT2="One", TPE1="Reorder Artist",
              TPE2="Reorder Artist", TALB="Reorder Album", TYER="2024", TRCK="01/3")
    _make_mp3(album / "02. Reorder Artist - Two.mp3", TIT2="Two", TPE1="Reorder Artist",
              TPE2="Reorder Artist", TALB="Reorder Album", TYER="2024", TRCK="02/3")
    _make_mp3(album / "03. Reorder Artist - Three.mp3", TIT2="Three", TPE1="Reorder Artist",
              TPE2="Reorder Artist", TALB="Reorder Album", TYER="2024", TRCK="03/3")

    # New order: Three, One, Two (a swap that would collide with naive renaming).
    order = [str(album / "03. Reorder Artist - Three.mp3"),
             str(album / "01. Reorder Artist - One.mp3"),
             str(album / "02. Reorder Artist - Two.mp3")]
    resp = client.post("/api/album/reorder", json={"path": str(album), "order": order})
    assert resp.status_code == 200 and resp.json()["ok"], resp.json()

    names = sorted(p.name for p in album.glob("*.mp3"))
    assert names == ["01. Reorder Artist - Three.mp3",
                     "02. Reorder Artist - One.mp3",
                     "03. Reorder Artist - Two.mp3"]
    t1 = ID3(album / "01. Reorder Artist - Three.mp3", translate=False)
    assert str(t1.get("TIT2")) == "Three" and str(t1.get("TRCK")) == "01/3"


def test_album_reorder_rejects_outside_album(client, tmp_path):
    tree = client.get("/api/tree").json()
    album = tree["artists"][0]["children"][0]["path"]
    resp = client.post("/api/album/reorder",
                       json={"path": album, "order": ["/etc/passwd"]})
    assert resp.status_code in (400, 403)


def test_import_merges_discs_in_order(tmp_path, tmp_path_factory):
    src = tmp_path_factory.mktemp("multidisc")
    common = dict(TPE1="Band", TPE2="Band", TALB="Live", TYER="2003", TCON="Rock")
    _make_mp3(src / "CD2" / "a.mp3", TIT2="D2T1", TPOS="2/2", TRCK="1", **common)
    _make_mp3(src / "CD1" / "b.mp3", TIT2="D1T1", TPOS="1/2", TRCK="1", **common)
    server.set_root(tmp_path)
    c = TestClient(server.app, client=("127.0.0.1", 12345))

    seen = {}

    def answer(prompt):
        if prompt["kind"] == "preview":
            # Both discs serialize with the same destination (one merged album).
            seen["n"] = len(prompt["entries"])
            return {"proceed": True, "entries": prompt["entries"]}
        if prompt["kind"] == "choice" and prompt["options"]:
            return prompt["options"][0]["key"]
        return ""

    jid = c.post("/api/jobs", json={"kind": "import", "source": str(src)}).json()["job_id"]
    assert _poll(c, jid, answer)["state"] == "done"
    dest = tmp_path / "Band" / "2003 - Live"
    names = sorted(p.name for p in dest.glob("*.mp3"))
    assert len(names) == 2
    # Disc 1 track numbered before disc 2 in the single merged album.
    assert ID3(dest / names[0], translate=False).get("TIT2").text[0] == "D1T1"
    assert ID3(dest / names[1], translate=False).get("TIT2").text[0] == "D2T1"


def test_import_order_honored(tmp_path, tmp_path_factory):
    src = tmp_path_factory.mktemp("ordersrc")
    _make_mp3(src / "a.mp3", TIT2="Aaa", TPE1="Ord", TPE2="Ord", TALB="OrdAlbum",
              TYER="2020", TRCK="1")
    _make_mp3(src / "b.mp3", TIT2="Bbb", TPE1="Ord", TPE2="Ord", TALB="OrdAlbum",
              TYER="2020", TRCK="2")
    _make_mp3(src / "c.mp3", TIT2="Ccc", TPE1="Ord", TPE2="Ord", TALB="OrdAlbum",
              TYER="2020", TRCK="3")
    server.set_root(tmp_path)
    c = TestClient(server.app, client=("127.0.0.1", 12345))

    # Submit in a known shuffled preview order: Ccc, Aaa, Bbb.
    submitted = ["Ccc", "Aaa", "Bbb"]

    def answer(prompt):
        if prompt["kind"] == "preview":
            rows = prompt["entries"]
            rows.sort(key=lambda r: submitted.index(r["title"]))
            return {"proceed": True, "entries": rows}
        if prompt["kind"] == "choice" and prompt["options"]:
            return prompt["options"][0]["key"]
        return ""

    jid = c.post("/api/jobs", json={"kind": "import", "source": str(src)}).json()["job_id"]
    assert _poll(c, jid, answer)["state"] == "done"
    dest = tmp_path / "Ord" / "2020 - OrdAlbum"
    # The on-disk track numbers must match the submitted (preview) order exactly.
    for n, title in enumerate(submitted, 1):
        f = dest / f"0{n}. Ord - {title}.mp3"
        assert f.is_file(), sorted(p.name for p in dest.glob("*.mp3"))
        assert str(ID3(f, translate=False).get("TRCK")) == f"0{n}/3"


def test_album_delete_and_prunes_artist(client, tmp_path):
    tree = client.get("/api/tree").json()
    album_path = tree["artists"][0]["children"][0]["path"]
    resp = client.post("/api/album/delete", json={"path": album_path})
    assert resp.status_code == 200 and resp.json()["ok"]
    assert not Path(album_path).exists()
    # It was the artist's only album → the empty artist folder is pruned.
    assert not (tmp_path / "Test Artist").exists()


def test_album_delete_rejects_artist_dir(client, tmp_path):
    # An artist-level path (parent == ROOT) must not be deletable.
    resp = client.post("/api/album/delete", json={"path": str(tmp_path / "Test Artist")})
    assert resp.status_code == 400
    assert (tmp_path / "Test Artist").is_dir()


def test_album_delete_rejects_outside_root(client):
    assert client.post("/api/album/delete", json={"path": "/etc"}).status_code == 403


def test_edit_unknown_op_400(client):
    tree = client.get("/api/tree").json()
    album_path = tree["artists"][0]["children"][0]["path"]
    resp = client.post("/api/edit/apply",
                       json={"path": album_path, "op": "bogus", "value": "x"})
    assert resp.status_code == 400


# ── Audit ─────────────────────────────────────────────────────────────────────

def test_audit_returns_categories(client):
    data = client.get("/api/audit").json()
    assert "category_labels" in data and data["category_labels"]
    assert set(data["totals"]) == {"albums", "albums_with_issues", "files", "files_with_issues"}


# ── Jobs ──────────────────────────────────────────────────────────────────────

def test_standardize_dry_run_job(client):
    jid = client.post("/api/jobs", json={"kind": "standardize", "dry_run": True}).json()["job_id"]
    j = _poll(client, jid)
    assert j["state"] == "done", j.get("error")
    assert j["log"], "expected captured log output"


def test_standardize_prompt_roundtrip(tmp_path):
    # A file missing TIT2 forces step 2 (fix missing tags) to prompt.
    album = tmp_path / "Artist" / "2024 - Album"
    _make_mp3(album / "01. Artist - Track.mp3",
              TPE1="Artist", TPE2="Artist", TALB="Album", TYER="2024", TRCK="01/1")
    server.set_root(tmp_path)
    c = TestClient(server.app, client=("127.0.0.1", 12345))

    asked = []

    def answer(prompt):
        asked.append(prompt["kind"])
        if prompt["kind"] == "text" and "Title" in prompt["prompt"]:
            return "Filled In"
        if prompt["kind"] == "choice" and prompt["options"]:
            return prompt["options"][0]["key"]
        return ""

    jid = c.post("/api/jobs", json={"kind": "standardize", "dry_run": False}).json()["job_id"]
    j = _poll(c, jid, answer)
    assert j["state"] == "done", j.get("error")
    assert "text" in asked, "expected at least one text prompt"
    # The title we supplied should now be on disk (file likely renamed to match).
    written = list((tmp_path / "Artist").rglob("*.mp3"))
    assert written
    tags = ID3(written[0], translate=False)
    assert str(tags.get("TIT2")) == "Filled In"


def test_import_job_copies_file(tmp_path, tmp_path_factory):
    src = tmp_path_factory.mktemp("source")
    _make_mp3(src / "song.mp3", TIT2="Imported", TPE1="Imp", TPE2="Imp",
              TALB="ImpAlbum", TYER="2020", TRCK="1")
    server.set_root(tmp_path)
    c = TestClient(server.app, client=("127.0.0.1", 12345))

    def answer(prompt):
        if prompt["kind"] == "preview":
            return {"proceed": True, "entries": prompt["entries"]}
        if prompt["kind"] == "choice" and prompt["options"]:
            return prompt["options"][0]["key"]
        return ""

    jid = c.post("/api/jobs",
                 json={"kind": "import", "source": str(src), "dry_run": False}).json()["job_id"]
    j = _poll(c, jid, answer)
    assert j["state"] == "done", j.get("error")
    imported = list(tmp_path.rglob("*.mp3"))
    assert imported, "expected an imported file in the library"


def test_import_via_upload(tmp_path, tmp_path_factory):
    # Build a real MP3 on disk, then upload its bytes through the drag-drop endpoints.
    staging = tmp_path_factory.mktemp("staging")
    _make_mp3(staging / "song.mp3", TIT2="Dropped", TPE1="Dee", TPE2="Dee",
              TALB="DropAlbum", TYER="2021", TRCK="1")
    server.set_root(tmp_path)
    c = TestClient(server.app, client=("127.0.0.1", 12345))

    token = c.post("/api/import/upload/start").json()["token"]
    upload_dir = server._UPLOADS[token]
    up = c.post("/api/import/upload/file",
                params={"token": token, "path": "DropAlbum/song.mp3"},
                content=(staging / "song.mp3").read_bytes(),
                headers={"Content-Type": "audio/mpeg"})
    assert up.status_code == 200
    assert (upload_dir / "DropAlbum" / "song.mp3").is_file()

    def answer(prompt):
        if prompt["kind"] == "preview":
            return {"proceed": True, "entries": prompt["entries"]}
        if prompt["kind"] == "choice" and prompt["options"]:
            return prompt["options"][0]["key"]
        return ""

    jid = c.post("/api/jobs",
                 json={"kind": "import", "upload_token": token}).json()["job_id"]
    j = _poll(c, jid, answer)
    assert j["state"] == "done", j.get("error")
    assert list(tmp_path.rglob("*.mp3")), "expected an imported file in the library"
    assert not upload_dir.exists(), "temp upload dir should be cleaned up after import"


def test_import_preview_edits_genre(tmp_path, tmp_path_factory):
    src = tmp_path_factory.mktemp("source")
    _make_mp3(src / "song.mp3", TIT2="Tune", TPE1="Band", TPE2="Band",
              TALB="Rec", TYER="2022", TRCK="1")
    server.set_root(tmp_path)
    c = TestClient(server.app, client=("127.0.0.1", 12345))

    def answer(prompt):
        if prompt["kind"] == "preview":
            entries = prompt["entries"]
            assert "genre" in entries[0]            # genre round-trips
            for e in entries:
                e["genre"] = "Jazz"
            return {"proceed": True, "entries": entries}
        if prompt["kind"] == "choice" and prompt["options"]:
            return prompt["options"][0]["key"]
        return ""

    jid = c.post("/api/jobs",
                 json={"kind": "import", "source": str(src)}).json()["job_id"]
    j = _poll(c, jid, answer)
    assert j["state"] == "done", j.get("error")
    imported = list(tmp_path.rglob("*.mp3"))
    assert imported
    assert str(ID3(imported[0], translate=False).get("TCON")) == "Jazz"


def test_import_preview_serializes_new_fields(tmp_path, tmp_path_factory):
    src = tmp_path_factory.mktemp("source")
    _make_mp3(src / "song.mp3", TIT2="T", TPE1="A", TPE2="A", TALB="Al", TYER="2020", TRCK="1")
    server.set_root(tmp_path)
    c = TestClient(server.app, client=("127.0.0.1", 12345))

    seen = {}

    def answer(prompt):
        if prompt["kind"] == "preview":
            seen["default_bitrate"] = prompt.get("default_bitrate")
            seen["row0"] = prompt["entries"][0]
            return {"proceed": True, "entries": prompt["entries"]}
        if prompt["kind"] == "choice" and prompt["options"]:
            return prompt["options"][0]["key"]
        return ""

    jid = c.post("/api/jobs", json={"kind": "import", "source": str(src)}).json()["job_id"]
    assert _poll(c, jid, answer)["state"] == "done"
    assert seen["default_bitrate"] == 320
    assert seen["row0"]["lossless"] is False
    assert "conflict" in seen["row0"]


def test_import_conflict_skip_and_add(tmp_path, tmp_path_factory):
    # Pre-existing album in the library (dest derived from tags: Imp / 2020 - ImpAlbum).
    dest = tmp_path / "Imp" / "2020 - ImpAlbum"
    _make_mp3(dest / "01. Imp - Old.mp3", TIT2="Old", TPE1="Imp", TPE2="Imp",
              TALB="ImpAlbum", TYER="2020", TRCK="01/1")
    server.set_root(tmp_path)
    c = TestClient(server.app, client=("127.0.0.1", 12345))

    def run(resolution):
        src = tmp_path_factory.mktemp("src")
        _make_mp3(src / "new.mp3", TIT2="New", TPE1="Imp", TPE2="Imp",
                  TALB="ImpAlbum", TYER="2020", TRCK="1")

        def answer(prompt):
            if prompt["kind"] == "preview":
                rows = prompt["entries"]
                assert rows[0]["conflict"] is True       # dest already exists
                for r in rows:
                    r["conflict"] = resolution
                return {"proceed": True, "entries": rows}
            if prompt["kind"] == "choice" and prompt["options"]:
                return prompt["options"][0]["key"]
            return ""

        jid = c.post("/api/jobs", json={"kind": "import", "source": str(src)}).json()["job_id"]
        assert _poll(c, jid, answer)["state"] == "done"

    run("skip")
    assert len(list(dest.glob("*.mp3"))) == 1           # skipped: untouched
    run("add")
    assert len(list(dest.glob("*.mp3"))) == 2           # added: appended


def test_import_lossless_bitrate_not_dropped(tmp_path, tmp_path_factory):
    src = tmp_path_factory.mktemp("flacsrc")
    _make_flac(src / "track.flac", title="Song", artist="Band",
               albumartist="Band", album="FlacAlbum", date="2019", tracknumber="1")
    server.set_root(tmp_path)
    c = TestClient(server.app, client=("127.0.0.1", 12345))

    def answer(prompt):
        if prompt["kind"] == "preview":
            rows = prompt["entries"]
            assert rows[0]["lossless"] is True
            for r in rows:
                r["bitrate"] = 128
            return {"proceed": True, "entries": rows}
        if prompt["kind"] == "choice" and prompt["options"]:
            return prompt["options"][0]["key"]
        return ""

    jid = c.post("/api/jobs", json={"kind": "import", "source": str(src)}).json()["job_id"]
    assert _poll(c, jid, answer)["state"] == "done"
    imported = list(tmp_path.rglob("*.mp3"))
    assert imported, "lossless entry must import (not be dropped) when a bitrate is set"


def test_import_art_none_writes_placeholder(tmp_path, tmp_path_factory):
    pytest.importorskip("PIL")
    src = tmp_path_factory.mktemp("noart")
    _make_mp3(src / "song.mp3", TIT2="T", TPE1="Solo", TPE2="Solo",
              TALB="NoArt", TYER="2020", TRCK="1")
    server.set_root(tmp_path)
    c = TestClient(server.app, client=("127.0.0.1", 12345))

    def answer(prompt):
        if prompt["kind"] == "preview":
            rows = prompt["entries"]
            for r in rows:
                r["art_none"] = True
            return {"proceed": True, "entries": rows}
        if prompt["kind"] == "choice" and prompt["options"]:
            return prompt["options"][0]["key"]
        return ""

    jid = c.post("/api/jobs", json={"kind": "import", "source": str(src)}).json()["job_id"]
    assert _poll(c, jid, answer)["state"] == "done"
    assert (tmp_path / "Solo" / "2020 - NoArt" / "cover.jpg").is_file()


def test_import_upload_rejects_traversal(client):
    token = client.post("/api/import/upload/start").json()["token"]
    resp = client.post("/api/import/upload/file",
                       params={"token": token, "path": "../evil.mp3"},
                       content=b"x", headers={"Content-Type": "audio/mpeg"})
    assert resp.status_code == 400


def test_import_cover_endpoint(client, tmp_path, monkeypatch):
    src = tmp_path / "incoming" / "Album"
    src.mkdir(parents=True)
    (src / "cover.jpg").write_bytes(b"\xff\xd8\xff\xe0jpegdata")
    # No active import → 404.
    monkeypatch.setattr(server, "_IMPORT_SOURCE", None)
    assert client.get("/api/import/cover", params={"path": str(src)}).status_code == 404
    # Bounded to the import source.
    monkeypatch.setattr(server, "_IMPORT_SOURCE", tmp_path / "incoming")
    ok = client.get("/api/import/cover", params={"path": str(src)})
    assert ok.status_code == 200 and ok.content == b"\xff\xd8\xff\xe0jpegdata"
    # Outside the source → 403.
    assert client.get("/api/import/cover", params={"path": "/etc"}).status_code == 403


def test_import_upload_unknown_token(client):
    resp = client.post("/api/import/upload/file",
                       params={"token": "nope", "path": "a.mp3"},
                       content=b"x")
    assert resp.status_code == 404


def test_second_job_conflict(client):
    # Start an import that will block on the preview prompt, then a second start -> 409.
    # Use a source with one file so it reaches the preview and waits.
    import tempfile
    src = tempfile.mkdtemp()
    _make_mp3(__import__("pathlib").Path(src) / "s.mp3",
              TIT2="A", TPE1="B", TPE2="B", TALB="C", TYER="2020", TRCK="1")
    first = client.post("/api/jobs", json={"kind": "import", "source": src}).json()["job_id"]
    # wait until it is waiting on preview
    for _ in range(200):
        if client.get(f"/api/jobs/{first}").json()["state"] == "waiting":
            break
        time.sleep(0.02)
    resp = client.post("/api/jobs", json={"kind": "standardize", "dry_run": True})
    assert resp.status_code == 409
    client.post(f"/api/jobs/{first}/cancel")  # release
    shutil.rmtree(src, ignore_errors=True)


# ── Sync ──────────────────────────────────────────────────────────────────────

def _sync_client(tmp_path):
    _make_mp3(tmp_path / "Artist One" / "2019 - First" / "01. A - S.mp3")
    _make_mp3(tmp_path / "Artist One" / "2021 - Second" / "01. A - S.mp3")
    _make_mp3(tmp_path / "Artist Two" / "2020 - Solo" / "01. A - S.mp3")
    server.set_root(tmp_path)
    return TestClient(server.app, client=("127.0.0.1", 12345))


def test_sync_artists_and_albums(tmp_path, tmp_path_factory):
    c = _sync_client(tmp_path)
    dev = tmp_path_factory.mktemp("device")
    data = c.get("/api/sync/artists", params={"device": str(dev)}).json()
    names = sorted(a["name"] for a in data["artists"])
    assert names == ["Artist One", "Artist Two"]
    assert all(a["status"] == "not on device" for a in data["artists"])

    albums = c.get("/api/sync/albums",
                   params={"artist": str(tmp_path / "Artist One"), "device": str(dev)}).json()
    assert albums["has_albums"]
    assert sorted(x["name"] for x in albums["albums"]) == ["2019 - First", "2021 - Second"]


def test_sync_plan_and_job_copies(tmp_path, tmp_path_factory):
    c = _sync_client(tmp_path)
    dev = tmp_path_factory.mktemp("device")
    selection = {
        str(tmp_path / "Artist One"): "all",
        str(tmp_path / "Artist Two"): [str(tmp_path / "Artist Two" / "2020 - Solo")],
    }
    plan = c.post("/api/sync/plan", json={"device": str(dev), "selection": selection}).json()
    assert plan["copy_files"] == 3 and plan["enough_space"]

    jid = c.post("/api/jobs",
                 json={"kind": "sync", "device": str(dev), "selection": selection}).json()["job_id"]
    j = _poll(c, jid)
    assert j["state"] == "done", j.get("error")
    copied = sorted(str(p.relative_to(dev)) for p in dev.rglob("*.mp3"))
    assert copied == [
        "Artist One/2019 - First/01. A - S.mp3",
        "Artist One/2021 - Second/01. A - S.mp3",
        "Artist Two/2020 - Solo/01. A - S.mp3",
    ]


def test_sync_device_inside_library_rejected(tmp_path):
    c = _sync_client(tmp_path)
    resp = c.get("/api/sync/artists", params={"device": str(tmp_path / "Artist One")})
    assert resp.status_code == 400


def test_sync_devices_endpoint(client):
    data = client.get("/api/sync/devices").json()
    assert "devices" in data and isinstance(data["devices"], list)


def test_edits_blocked_while_job_active(client, tmp_path):
    # Start an import that parks on the preview prompt, so a job is "active".
    import tempfile
    src = tempfile.mkdtemp()
    _make_mp3(Path(src) / "s.mp3", TIT2="A", TPE1="B", TPE2="B",
              TALB="C", TYER="2020", TRCK="1")
    jid = client.post("/api/jobs", json={"kind": "import", "source": src}).json()["job_id"]
    for _ in range(200):
        if client.get(f"/api/jobs/{jid}").json()["state"] == "waiting":
            break
        time.sleep(0.02)

    # /api/jobs/active reports it.
    active = client.get("/api/jobs/active").json()["active"]
    assert active and active["id"] == jid and active["kind"] == "import"

    # Library-mutating endpoints are rejected with 409 while it runs.
    tree = client.get("/api/tree").json()
    album = tree["artists"][0]["children"][0]["path"]
    track = client.get("/api/album", params={"path": album}).json()["tracks"][0]["path"]
    assert client.post("/api/tags", json={"path": track, "updates": {"TIT2": "X"}}).status_code == 409
    assert client.post("/api/edit/apply",
                       json={"path": album, "op": "album_genre", "value": "Z"}).status_code == 409

    client.post(f"/api/jobs/{jid}/cancel")
    shutil.rmtree(src, ignore_errors=True)


# ── LAN guest gating (loopback = owner, other IPs = read-only) ────────────────

def test_whoami_owner_vs_guest(client, guest):
    assert client.get("/api/whoami").json()["trusted"] is True
    assert guest.get("/api/whoami").json()["trusted"] is False


def test_guest_can_browse_and_play(client, guest):
    tree = guest.get("/api/tree")
    assert tree.status_code == 200
    album_path = tree.json()["artists"][0]["children"][0]["path"]
    assert guest.get("/api/album", params={"path": album_path}).status_code == 200
    track_path = guest.get("/api/album", params={"path": album_path}) \
        .json()["tracks"][0]["path"]
    # Audio streams with Range support so seeking works.
    r = guest.get("/api/track", params={"path": track_path},
                  headers={"Range": "bytes=0-99"})
    assert r.status_code in (200, 206)
    assert guest.get("/api/search", params={"q": "Silent"}).status_code == 200


def test_guest_blocked_from_admin(client, guest):
    album = client.get("/api/tree").json()["artists"][0]["children"][0]["path"]
    track = client.get("/api/album", params={"path": album}).json()["tracks"][0]["path"]
    # Read-only audit is a GET but still owner-only (default-deny).
    assert guest.get("/api/audit").status_code == 403
    # Mutations are all blocked.
    assert guest.post("/api/tags",
                      json={"path": track, "updates": {"TIT2": "x"}}).status_code == 403
    assert guest.post("/api/settings", json={"cover_art": "embed"}).status_code == 403
    assert guest.post("/api/edit/apply",
                      json={"path": album, "op": "album_genre", "value": "Z"}).status_code == 403
    assert guest.post("/api/jobs", json={"kind": "standardize"}).status_code == 403
    assert guest.get("/api/sync/devices").status_code == 403
    # The owner is unaffected by the guest gate.
    assert client.get("/api/audit").status_code == 200


def test_guest_settings_sanitized(client, guest):
    full = client.get("/api/settings").json()
    assert "art_sources" in full                 # owner sees everything
    g = guest.get("/api/settings")
    assert g.status_code == 200                   # guests may read display fields
    body = g.json()
    assert "art_sources" not in body
    assert "art_source_order" not in body
    assert not any(s in k.lower() for k in body for s in ("token", "key", "secret"))


# ── Collections ───────────────────────────────────────────────────────────────

def _album_path(client):
    return client.get("/api/tree").json()["artists"][0]["children"][0]["path"]


def test_collections_owner_crud(client):
    assert client.get("/api/collections").json()["collections"] == []

    r = client.post("/api/collection/create", json={"name": "Faves"})
    assert r.status_code == 200
    assert [c["name"] for c in r.json()["collections"]] == ["Faves"]

    album = _album_path(client)
    r = client.post("/api/collection/add", json={"name": "Faves", "album_path": album})
    assert r.status_code == 200
    assert r.json()["collections"][0]["count"] == 1

    data = client.get("/api/collection", params={"name": "Faves"}).json()
    assert data["collection"] == "Faves"
    assert len(data["albums"]) == 1
    assert data["albums"][0]["album_path"] == album

    r = client.post("/api/collection/remove", json={"name": "Faves", "album_path": album})
    assert r.json()["collections"][0]["count"] == 0

    client.post("/api/collection/rename", json={"name": "Faves", "new_name": "Best"})
    assert [c["name"] for c in client.get("/api/collections").json()["collections"]] == ["Best"]

    client.post("/api/collection/delete", json={"name": "Best"})
    assert client.get("/api/collections").json()["collections"] == []


def test_collection_create_duplicate_400(client):
    client.post("/api/collection/create", json={"name": "Faves"})
    r = client.post("/api/collection/create", json={"name": "faves"})
    assert r.status_code == 400


def test_collection_add_outside_library_403(client):
    client.post("/api/collection/create", json={"name": "Faves"})
    r = client.post("/api/collection/add", json={"name": "Faves", "album_path": "/etc"})
    assert r.status_code == 403         # _safe rejects paths outside the library root


def test_collection_persists_to_settings(client, tmp_path):
    import settings as settings_mod
    client.post("/api/collection/create", json={"name": "Faves"})
    assert [c["name"] for c in settings_mod.load(tmp_path)["collections"]] == ["Faves"]


def test_guest_can_browse_collections(client, guest):
    client.post("/api/collection/create", json={"name": "Faves"})
    client.post("/api/collection/add", json={"name": "Faves", "album_path": _album_path(client)})
    assert guest.get("/api/collections").status_code == 200
    data = guest.get("/api/collection", params={"name": "Faves"}).json()
    assert len(data["albums"]) == 1


@pytest.mark.parametrize("path,body", [
    ("/api/collection/create", {"name": "X"}),
    ("/api/collection/rename", {"name": "Faves", "new_name": "Y"}),
    ("/api/collection/delete", {"name": "Faves"}),
    ("/api/collection/add", {"name": "Faves", "album_path": "x"}),
    ("/api/collection/remove", {"name": "Faves", "album_path": "x"}),
])
def test_guest_blocked_from_collection_mutations(guest, path, body):
    assert guest.post(path, json=body).status_code in (401, 403)
